#cloud-config
users:
  - name: yc-user
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAhNw3ATc/2kz+5pGp4+MxocDs36xcg/zGZ6dGx8F49Sqict6vAuVxoQXmG8z3yEvs4eJ8D7vo7quhs73W2Y2WiM5NZ8HU6foqnovlDsrmfJYyDZg6ZSyZL5abNmum/LTEPYr1lQV3AYdJVMPAAm3hqjPA0kQnYjmKiDTpFtVHuMtGdlTrlCoTeEi4H3mHQcPdj1v48eXPuZNVR6UPNnKlT2zhhJO3FS3W7Y3P8iu4LZI9z3xQOWiwYmZIui3MW/AeuwlJsD93wmfFw85mMvCUGuHLK8ldcUNwmY+iCday+1m7GfqBqH1EF7YTyMmoAdTaeP99XFZY9d/kHjlo4Dap appuser
write_files:
  - path: /home/yc-user/install_ruby.sh
    permissions: "0751"
    content: |
      #!/bin/bash
      apt update
      apt install -y ruby-full ruby-bundler build-essential
  - path: /home/yc-user/install_mongodb.sh
    permissions: "0751"
    content: |
      #!/bin/bash
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      apt update
      apt install -y mongodb-org
      systemctl start mongod
      systemctl enable mongod
  - path: /home/yc-user/deploy.sh
    permissions: "0751"
    content: |
      #!/bin/bash
      apt install -y git
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit && bundle install
      puma -d
runcmd:
  - sudo /home/yc-user/install_ruby.sh
  - sudo /home/yc-user/install_mongodb.sh
  - sudo /home/yc-user/deploy.sh
