---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  tasks:

  - name: Wait for automatic system updates
    shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
    with_items:
      - lock
      - lock-frontend

  - name: apt-get update
    shell: apt-get update -y

  - name: Install ruby, bundler and other soft
    apt: "name={{ item }} state=present"
    with_items:
      - apt-transport-https
      - ruby-full
      - ruby-bundler
      - git
      - build-essential
