---
- name: Install Ruby and Bundler
  hosts: app
  become: true
  tasks:
  - name: Install ruby, bundler and other soft
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - apt-transport-https
      - git
      - build-essential
