---
- name: Install MongoDB
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0
  become: true
  tasks:
    - name: install mongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: copy config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify:
        - restart mongod

    - name: enable mongod
      systemd: name=mongod enabled=yes

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
